//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfolineWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfolineWorkEntities : DbContext
    {
        public InfolineWorkEntities()
            : base("name=InfolineWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPerson> tblPerson { get; set; }
        public virtual DbSet<tblQuestion> tblQuestion { get; set; }
        public virtual DbSet<tblAnswer> tblAnswer { get; set; }
    }
}
